spring.application.name=demo

spring.datasource.url=jdbc:postgresql://localhost:5432/lungthly_db
spring.datasource.username=postgres
spring.datasource.password=san12345

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sq;=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
